<?php

define("DSPACE_RECORD_PROCESS_REQUEST", "dspace_record_process_request");

//Module Name
define("DSPACE", "dspace");

//Field Names
define("ITEM_AUTHOR_FIELD", "author");
define("ITEM_PUBLISHER_FIELD", "publisher");
define("ITEM_SUBJECT_FIELD", "dspace_subject");
define("ITEM_TOPIC_FIELD", "dspace_topic");
define("ITEM_REGION_FIELD", "dspace_region");
define("ITEM_LANGUAGE_FIELD", "dspace_language");

//Taxonomy Vocabulary Names
define("DSPACE_ITEM_SUBJECT", "dspace_subject");
define("DSPACE_ITEM_TOPIC", "dspace_topic");
define("DSPACE_ITEM_REGION", "dspace_region");
define("DSPACE_ITEM_LANGUAGE", "dspace_language");

//Entities
define("DSPACE_SET", "dspace_set");
define("DSPACE_PROCESS_RECORD", "dspace_process_record");
define("DSPACE_ITEM", "dspace_item");
define("DSPACE_AUTHOR", "dspace_author");
define("DSPACE_PUBLISHER", "dspace_publisher");

//Queues
define("DSPACE_SYNC", "dspace_sync");
define("DSPACE_QUEUE", "dspace_queue");
